<?php

use Illuminate\Database\Seeder;

class GPEPositionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * 
     * GPE Edition: IDs start at 1000
     * 
     * @return void
     */
    public function run()
    {
        // because our google spreadsheet outputs json and I'm lazy,
        // let's just parse that and import it.
        $json_import = <<<JSON
{
    "751": {
        "title": "Gate Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GSL",
        "id": 751,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "928": {
        "title": "Office Lead",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "OL",
        "id": 928,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "929": {
        "title": "Office Crew",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "OC",
        "id": 929,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "959": {
        "title": "Gate Lane Lead",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GLL",
        "id": 959,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "963": {
        "title": "Airport Gate Coordinator",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "AGC",
        "id": 963,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "964": {
        "title": "Airport Gate Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "AirC",
        "id": 964,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "965": {
        "title": "Exodus Operations Manager",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EOM",
        "id": 965,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "966": {
        "title": "Exodus Pulsers Lead",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EPL",
        "id": 966,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "968": {
        "title": "Exodus Lead",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EFL",
        "id": 968,
        "min": 1,
        "max": 0,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "970": {
        "title": "Exodus Setup",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EXOSET",
        "id": 970,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "971": {
        "title": "TOC Lead",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "TOCL",
        "id": 971,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "974": {
        "title": "Black Hole Operations Lead",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "BHOL",
        "id": 974,
        "min": 1,
        "max": 3,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "975": {
        "title": "Transpo Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "TSL",
        "id": 975,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "978": {
        "title": "Office Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "OS",
        "id": 978,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "981": {
        "title": "Point 1 Shift Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "SSP1",
        "id": 981,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "987": {
        "title": "Flagger Training",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "FT",
        "id": 987,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "990": {
        "title": "Fluffer Lead",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "FL",
        "id": 990,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "991": {
        "title": "Gateteria Driver",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "GD",
        "id": 991,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "992": {
        "title": "Lead Fluffer",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "LF",
        "id": 992,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "994": {
        "title": "Mentor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "MTT",
        "id": 994,
        "min": 1,
        "max": 0,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1001": {
        "title": "Lane 13 Lead",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "L13L",
        "id": 1001,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1004": {
        "title": "Exit Lane Lead",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "ELL",
        "id": 1004,
        "min": 1,
        "max": 0,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1005": {
        "title": "Perimeter Shift Supervisor",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "SLP",
        "id": 1005,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1006": {
        "title": "Perimeter Shift Supervisor Trainee",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "SLT",
        "id": 1006,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1010": {
        "title": "Perimeter Trainee",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PT",
        "id": 1010,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1011": {
        "title": "Perimeter Trainee",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PTRN",
        "id": 1011,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1016": {
        "title": "Gate Coordinator Training",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "GCT",
        "id": 1016,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1019": {
        "title": "Logistics Supervisor",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LLS",
        "id": 1019,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1020": {
        "title": "ERS",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "ERS",
        "id": 1020,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1021": {
        "title": "Logistics Road Crew",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LRC",
        "id": 1021,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1022": {
        "title": "Logistics Waste Supervisor",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LWS",
        "id": 1022,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1024": {
        "title": "LC",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LC",
        "id": 1024,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1030": {
        "title": "Setup Le",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "SLS",
        "id": 1030,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1031": {
        "title": "Setup lead Crew",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "SLC",
        "id": 1031,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1043": {
        "title": "Scanner Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "TCP",
        "id": 1043,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1229": {
        "title": "Bartender",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "BarT",
        "id": 1229,
        "min": 1,
        "max": 0,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1751": {
        "title": "Apex Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GAS",
        "id": 1751,
        "min": 1,
        "max": 1,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1753": {
        "title": "New Blood Trainee",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "TrainN",
        "id": 1753,
        "min": 1,
        "max": 0,
        "active": 0,
        "prevent_multiple_enrollments": 1
    },
    "1761": {
        "title": "Exit Lane Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "ELS",
        "id": 1761,
        "min": 1,
        "max": 3,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1778": {
        "title": "Office Crew",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "OfC",
        "id": 1778,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1779": {
        "title": "Office Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "OfS",
        "id": 1779,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1784": {
        "title": "Perimeter Shift Supervisor Trainee",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PSSt",
        "id": 1784,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1798": {
        "title": "Scanner Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "SSup",
        "id": 1798,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1803": {
        "title": "Will Call Lot Coordinator (old)",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "WCC",
        "id": 1803,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1814": {
        "title": "Office Coordinator",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "OCR",
        "id": 1814,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1821": {
        "title": "Masage Lead",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "MS",
        "id": 1821,
        "min": 1,
        "max": 1,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1852": {
        "title": "Black Hole Hair",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "BSH",
        "id": 1852,
        "min": 1,
        "max": 1,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1863": {
        "title": "Driver something BDT",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "BDT",
        "id": 1863,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1864": {
        "title": "Driver something BDP",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "BDP",
        "id": 1864,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "1865": {
        "title": "Driver something BDA",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "BDA",
        "id": 1865,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "2181": {
        "title": "Apex Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "AC",
        "id": 2181,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2182": {
        "title": "Apex Coordinator",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GAC",
        "id": 2182,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2184": {
        "title": "Bartender",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "Bar",
        "id": 2184,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2186": {
        "title": "Black Hole Administrative Lead",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "BHAL",
        "id": 2186,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2187": {
        "title": "Black Hole Operations Supervisor",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "BHoM",
        "id": 2187,
        "min": 1,
        "max": 3,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2188": {
        "title": "Bar Supervisor",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "BS",
        "id": 2188,
        "min": 1,
        "max": 3,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2190": {
        "title": "Fleet assistant",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "FLA",
        "id": 2190,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2191": {
        "title": "Black Hole Art Director",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "ART",
        "id": 2191,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2193": {
        "title": "Fleet Manager",
        "type": "Black Hole",
        "new_user_eligible": 0,
        "short_title": "FLM",
        "id": 2193,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2197": {
        "title": "Mentor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "MTR",
        "id": 2197,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2200": {
        "title": "Veteran department trainee",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "TrainR",
        "id": 2200,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 1
    },
    "2201": {
        "title": "Mentor Lead",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "MTL",
        "id": 2201,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2202": {
        "title": "D Lot Trainee",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "DLT",
        "id": 2202,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 1
    },
    "2203": {
        "title": "D Lot Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "DLC",
        "id": 2203,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2204": {
        "title": "D Lot Lead",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "DLL",
        "id": 2204,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2206": {
        "title": "Exit Lane Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "ELC",
        "id": 2206,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2207": {
        "title": "Exit Lane Coordinator",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "ELR",
        "id": 2207,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2209": {
        "title": "Exodus Flagger Crew",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EFC",
        "id": 2209,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2211": {
        "title": "Exodus Flagger Supervisor",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EFS",
        "id": 2211,
        "min": 4,
        "max": 8,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2212": {
        "title": "Exodus Setup",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EXOset",
        "id": 2212,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2213": {
        "title": "TOC Crew",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "TOC",
        "id": 2213,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2214": {
        "title": "TOC Lead",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "TOL",
        "id": 2214,
        "min": 4,
        "max": 8,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2216": {
        "title": "Exodus Pulsing Crew",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EPC",
        "id": 2216,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2217": {
        "title": "Exodus P1 Pulser",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EP1P",
        "id": 2217,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2218": {
        "title": "Exodus Traffic Counter",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "ETC",
        "id": 2218,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2219": {
        "title": "Exodus P1 Lead",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EP1L",
        "id": 2219,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2220": {
        "title": "Exodus Pulsing Supervisor",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "EPS",
        "id": 2220,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2221": {
        "title": "BMIT @ the Gate",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "BMIT",
        "id": 2221,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2222": {
        "title": "Early Gate Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "EGC",
        "id": 2222,
        "min": 1,
        "max": 0,
        "active": 0,
        "prevent_multiple_enrollments": 0
    },
    "2223": {
        "title": "Gate Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GC",
        "id": 2223,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2224": {
        "title": "Gate Lane Coordinator",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GLC",
        "id": 2224,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2225": {
        "title": "G13 Mentee",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "G13",
        "id": 2225,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2227": {
        "title": "Gate Lane Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GSS",
        "id": 2227,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2228": {
        "title": "L13 Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "L13aS",
        "id": 2228,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2229": {
        "title": "Lane 13 Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "L13S",
        "id": 2229,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2230": {
        "title": "Life Support Crew",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "LSC",
        "id": 2230,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2231": {
        "title": "Life Support Lead",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "LSL",
        "id": 2231,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2233": {
        "title": "Logistics Crew Lead",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LCL",
        "id": 2233,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2234": {
        "title": "Logistics Crew",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LCR",
        "id": 2234,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2235": {
        "title": "Logistics Assistant Supervisor",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LRaS",
        "id": 2235,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2236": {
        "title": "Logistics Road Supervisor",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LRS",
        "id": 2236,
        "min": 1,
        "max": 3,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2239": {
        "title": "Logistics Tech Lead",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LTL",
        "id": 2239,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2240": {
        "title": "Logistics Waste Assistant",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LWA",
        "id": 2240,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2241": {
        "title": "Logistics Waste Lead",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "LWL",
        "id": 2241,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2242": {
        "title": "Black Hole Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "BHM",
        "id": 2242,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2243": {
        "title": "Central Services Assistant Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "CAM",
        "id": 2243,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2244": {
        "title": "Central Services Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "CCM",
        "id": 2244,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2245": {
        "title": "Department Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "DPM",
        "id": 2245,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2246": {
        "title": "Exodus Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "EXM",
        "id": 2246,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2247": {
        "title": "Gate Assistant Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "GAM",
        "id": 2247,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2248": {
        "title": "Logistics Assistant Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "GLaM",
        "id": 2248,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2249": {
        "title": "Logistics Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "GLM",
        "id": 2249,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2250": {
        "title": "Gate Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "GMA",
        "id": 2250,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2251": {
        "title": "Logistics Admin Sup",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "LAS",
        "id": 2251,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2253": {
        "title": "Perimeter Assistant Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "PAM",
        "id": 2253,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2254": {
        "title": "Perimeter Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "PMA",
        "id": 2254,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2255": {
        "title": "Exodus Assistant Manager",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "XAM",
        "id": 2255,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2256": {
        "title": "Office Crew",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "CRW",
        "id": 2256,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2259": {
        "title": "Office Coordinator",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "COORD",
        "id": 2259,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2262": {
        "title": "Staging Lot Setup Crew",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "SLSC",
        "id": 2262,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2263": {
        "title": "Perimeter Shift Supervisor",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PSS",
        "id": 2263,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2264": {
        "title": "Perimeter G13 Trainee",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PG-13",
        "id": 2264,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2265": {
        "title": "Perimeter Driver",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "DRV",
        "id": 2265,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2266": {
        "title": "Perimeter Rider",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "RDR",
        "id": 2266,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2267": {
        "title": "Lighthouse Operator",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "LHO",
        "id": 2267,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2268": {
        "title": "Perimeter Mentor",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PMT",
        "id": 2268,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2270": {
        "title": "Perimeter Trainee",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PTE",
        "id": 2270,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2272": {
        "title": "Perimeter Trainee - New Blood",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "PTEnb",
        "id": 2272,
        "min": 1,
        "max": 48,
        "active": 1,
        "prevent_multiple_enrollments": 1
    },
    "2273": {
        "title": "Point 1 Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P1C",
        "id": 2273,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2274": {
        "title": "Point 1 Pre / Post",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P1PP",
        "id": 2274,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2275": {
        "title": "Point 1 Lead",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P1L",
        "id": 2275,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2277": {
        "title": "Point 5 Trianee",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P5N",
        "id": 2277,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2278": {
        "title": "Point 5 Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P5C",
        "id": 2278,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2279": {
        "title": "Point 5 Coordinator",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P5R",
        "id": 2279,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2281": {
        "title": "Scanner Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "SC",
        "id": 2281,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2288": {
        "title": "Transpo Bus Driver",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "TBD",
        "id": 2288,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2289": {
        "title": "Transpo Lead",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "TRL",
        "id": 2289,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2291": {
        "title": "Will Call Lot Crew",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "WC",
        "id": 2291,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2292": {
        "title": "Will Call Lot Coordinator",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "WCR",
        "id": 2292,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2295": {
        "title": "New Blood Trainee",
        "type": "Central Services",
        "new_user_eligible": 1,
        "short_title": "TrainN",
        "id": 2295,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 1
    },
    "2296": {
        "title": "Mentor Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "MTS",
        "id": 2296,
        "min": 1,
        "max": 3,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2298": {
        "title": "Perimeter Scout",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "Scout2",
        "id": 2298,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2300": {
        "title": "Apex Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "APS",
        "id": 2300,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2301": {
        "title": "Apex Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "APaS",
        "id": 2301,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2302": {
        "title": "Exit Lane Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "EXS",
        "id": 2302,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2303": {
        "title": "Exit Lane Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "EXaS",
        "id": 2303,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2305": {
        "title": "Point 1 Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P1S",
        "id": 2305,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2306": {
        "title": "Point 1 Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P1aS",
        "id": 2306,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2307": {
        "title": "Point 5 Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P5S",
        "id": 2307,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2308": {
        "title": "Point 5 Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "P5aS",
        "id": 2308,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2309": {
        "title": "Will Call Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "WCS",
        "id": 2309,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2310": {
        "title": "Will Call Lot Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "WCaS",
        "id": 2310,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2311": {
        "title": "D Lot Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "DLS",
        "id": 2311,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2312": {
        "title": "D Lot Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "DLaS",
        "id": 2312,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2313": {
        "title": "Traffic Operations Center Supervisor",
        "type": "Exodus",
        "new_user_eligible": 0,
        "short_title": "TOS",
        "id": 2313,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2314": {
        "title": "Gate Box Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "GBS",
        "id": 2314,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2315": {
        "title": "Gate Box Assistant Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "GBaS",
        "id": 2315,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2316": {
        "title": "Life Support Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "LSS",
        "id": 2316,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2317": {
        "title": "Life Support Assistant Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "LSaS",
        "id": 2317,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2349": {
        "title": "Sweeper Crew",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "SWP",
        "id": 2349,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2350": {
        "title": "Gate Lanes Supervisor Mentor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "GSM",
        "id": 2350,
        "min": 1,
        "max": 3,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2351": {
        "title": "CAD Designer",
        "type": "Logistics",
        "new_user_eligible": 0,
        "short_title": "CAD",
        "id": 2351,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2352": {
        "title": "Personnel Lead",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "PTL",
        "id": 2352,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2353": {
        "title": "Personnel Crew",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "PTC",
        "id": 2353,
        "min": 1,
        "max": 3,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2355": {
        "title": "Sweeper Coordinator",
        "type": "Perimeter",
        "new_user_eligible": 0,
        "short_title": "SWC",
        "id": 2355,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2356": {
        "title": "Babalooey Supervisor",
        "type": "Management",
        "new_user_eligible": 0,
        "short_title": "BBL",
        "id": 2356,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2357": {
        "title": "Scanners Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "TSP",
        "id": 2357,
        "min": 1,
        "max": 1,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2358": {
        "title": "Scanners Assistant Supervisor",
        "type": "Gate",
        "new_user_eligible": 0,
        "short_title": "TaSP",
        "id": 2358,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2359": {
        "title": "GateWear",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "GWAR",
        "id": 2359,
        "min": 2,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2367": {
        "title": "Healix crew",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "HLR",
        "id": 2367,
        "min": 1,
        "max": 0,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2368": {
        "title": "Healix Supervisor",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "HLS",
        "id": 2368,
        "min": 1,
        "max": 2,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2369": {
        "title": "VC Team",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "VCT",
        "id": 2369,
        "min": 1,
        "max": 4,
        "active": 1,
        "prevent_multiple_enrollments": 0
    },
    "2375": {
        "title": "MPB",
        "type": "Central Services",
        "new_user_eligible": 0,
        "short_title": "MPB",
        "id": 2375,
        "min": "0",
        "max": "0",
        "active": 0,
        "prevent_multiple_enrollments": 0
    }
}
JSON;
        $import_data = json_decode($json_import, true);
        echo "Importing JSON";
        echo "Error was", json_last_error_msg();

        DB::table('position')->where('id', '>=', '1000')->delete();        
        foreach($import_data as $line) {
            DB::table('position')->insert(array($line));
        }
    }
}
 