<?php

use Illuminate\Database\Seeder;

class PositionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('position')->delete();
        
        \DB::table('position')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Alpha',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Dirt',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'Dirt',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'HQ Window',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => 31,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Dirt - Green Dot',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'GD',
                'type' => 'Frontline',
                'training_position_id' => 101,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Intercept',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'Int',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Intercept Dispatch',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'IntDsp',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'LEAL',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'LEAL',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'LEAL Mentee',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'LEALTr',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Mentor',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'OOD',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'OOD',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'RNR',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'RNR',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'RSC Shift Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'RSL',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Training',
                'new_user_eligible' => 1,
                'all_rangers' => 1,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Green Dot Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'GDLead',
                'type' => 'Command',
                'training_position_id' => 101,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Mentor - Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Art Safety',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'ArtSaf',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Echelon Field',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'HQ Runner',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Burn Perimeter',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Tow Truck Driver',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'Tow',
                'type' => 'Frontline',
                'training_position_id' => 102,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => '007',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => '007',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'title' => 'Trainer',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'title' => 'Tech Team',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'title' => 'RSCI',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'RSCI',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            24 => 
            array (
                'id' => 27,
                'title' => 'Special Burn',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'SpcBrn',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            25 => 
            array (
                'id' => 28,
                'title' => 'Green Dot Long',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'GDL',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            26 => 
            array (
                'id' => 31,
                'title' => 'HQ Training',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            27 => 
            array (
                'id' => 32,
                'title' => 'HQ Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => 31,
            ),
            28 => 
            array (
                'id' => 33,
                'title' => 'HQ Short',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => 31,
            ),
            29 => 
            array (
                'id' => 34,
                'title' => 'HQ Trainer',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            30 => 
            array (
                'id' => 35,
                'title' => 'Mentor - Short ',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            31 => 
            array (
                'id' => 37,
                'title' => 'Operations Manager',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'ROM',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            32 => 
            array (
                'id' => 38,
                'title' => 'Deep Freeze',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Other',
                'training_position_id' => NULL,
            ),
            33 => 
            array (
                'id' => 39,
                'title' => 'Hot Springs Patrol Driver',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'HSP',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            34 => 
            array (
                'id' => 40,
                'title' => 'Green Dot Mentor',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'GDMntr',
                'type' => 'Frontline',
                'training_position_id' => 101,
            ),
            35 => 
            array (
                'id' => 42,
                'title' => 'Logistics',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            36 => 
            array (
                'id' => 43,
                'title' => 'Gate Opening',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            37 => 
            array (
                'id' => 45,
                'title' => 'Cheetah',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            38 => 
            array (
                'id' => 46,
                'title' => 'Cheetah Cub',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            39 => 
            array (
                'id' => 49,
            'title' => 'HQ Training (Refresher)',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => NULL,
            ),
            40 => 
            array (
                'id' => 50,
                'title' => 'Green Dot Mentee',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'GDMnte',
                'type' => 'Frontline',
                'training_position_id' => 101,
            ),
            41 => 
            array (
                'id' => 51,
                'title' => 'HQ Supervisor',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => 31,
            ),
            42 => 
            array (
                'id' => 53,
                'title' => 'Dirt - Pre-event',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 0,
                'short_title' => 'DrtPre',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            43 => 
            array (
                'id' => 54,
                'title' => 'Sanctuary',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'Sanc',
                'type' => 'Frontline',
                'training_position_id' => 101,
            ),
            44 => 
            array (
                'id' => 56,
                'title' => 'Operator',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'Opr',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            45 => 
            array (
                'id' => 59,
                'title' => 'SITE Setup',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            46 => 
            array (
                'id' => 60,
                'title' => 'SITE Teardown',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            47 => 
            array (
                'id' => 61,
                'title' => 'Sandman',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => 'Sndman',
                'type' => 'Frontline',
                'training_position_id' => 80,
            ),
            48 => 
            array (
                'id' => 62,
                'title' => 'IMS Training',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            49 => 
            array (
                'id' => 63,
                'title' => 'Personnel Manager',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 2,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'PM',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            50 => 
            array (
                'id' => 64,
                'title' => 'RSCI FB Counselor',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            51 => 
            array (
                'id' => 65,
                'title' => 'Dirt - Orange Dot',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 0,
                'short_title' => 'Orange',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            52 => 
            array (
                'id' => 66,
                'title' => 'Intercept Operator',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 3,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'IntOpr',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            53 => 
            array (
                'id' => 67,
                'title' => 'Mentor - MITten',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            54 => 
            array (
                'id' => 68,
                'title' => 'Sanctuary Host',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 0,
                'short_title' => 'SancLd',
                'type' => 'Frontline',
                'training_position_id' => 101,
            ),
            55 => 
            array (
                'id' => 69,
                'title' => 'Tow Truck Mentee',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'TowMnt',
                'type' => 'Frontline',
                'training_position_id' => 102,
            ),
            56 => 
            array (
                'id' => 70,
                'title' => 'Mentor - Apprentice',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 2,
                'auto_signout' => 1,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            57 => 
            array (
                'id' => 71,
                'title' => 'RSC Dispatch',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'Dspch',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            58 => 
            array (
                'id' => 72,
                'title' => 'Mentor - Radio Trainer',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            59 => 
            array (
                'id' => 73,
                'title' => 'LNT Outreach',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 0,
                'short_title' => 'LNT',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            60 => 
            array (
                'id' => 74,
                'title' => 'Vehicle Maintenance',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            61 => 
            array (
                'id' => 75,
                'title' => 'Gerlach Patrol',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'GerPat',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            62 => 
            array (
                'id' => 76,
                'title' => 'Gerlach Patrol Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 1,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'GerLd',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            63 => 
            array (
                'id' => 77,
                'title' => 'RSC Resident',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'Resdnt',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            64 => 
            array (
                'id' => 78,
                'title' => 'RSC Shift Coord',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 3,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'SC',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            65 => 
            array (
                'id' => 80,
                'title' => 'Sandman Training',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            66 => 
            array (
                'id' => 81,
                'title' => 'Echelon Field Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            67 => 
            array (
                'id' => 82,
                'title' => 'Personnel Investigator',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            68 => 
            array (
                'id' => 83,
                'title' => 'RSC Shift Lead -Pre-event',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 0,
                'short_title' => 'RSLPre',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            69 => 
            array (
                'id' => 84,
                'title' => 'Quartermaster',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 0,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            70 => 
            array (
                'id' => 85,
                'title' => 'LEAL Mentor',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'LEALMn',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            71 => 
            array (
                'id' => 86,
                'title' => 'Mentor - Khaki',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 1,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Mentoring',
                'training_position_id' => NULL,
            ),
            72 => 
            array (
                'id' => 87,
                'title' => 'Deputy OOD',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'DOOD',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            73 => 
            array (
                'id' => 88,
                'title' => 'Trainer - Associate',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            74 => 
            array (
                'id' => 89,
                'title' => 'IMS Admin',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            75 => 
            array (
                'id' => 90,
                'title' => 'IMS Audit',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            76 => 
            array (
                'id' => 91,
                'title' => 'Troubleshooter',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'TShoot',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            77 => 
            array (
                'id' => 92,
                'title' => 'RSCI Mentor',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            78 => 
            array (
                'id' => 93,
                'title' => 'RSCI Mentee',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'RSCIM',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            79 => 
            array (
                'id' => 94,
                'title' => 'Troubleshooter Training',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 5,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            80 => 
            array (
                'id' => 95,
                'title' => 'Trainer - Uber',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            81 => 
            array (
                'id' => 96,
                'title' => 'SITE Setup Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            82 => 
            array (
                'id' => 97,
                'title' => 'SITE Teardown Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            83 => 
            array (
                'id' => 98,
                'title' => 'Logistics Lead',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            84 => 
            array (
                'id' => 99,
                'title' => 'Burn Command Team',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            85 => 
            array (
                'id' => 100,
                'title' => 'Green Dot Trainer',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            86 => 
            array (
                'id' => 101,
                'title' => 'Green Dot Training',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            87 => 
            array (
                'id' => 102,
                'title' => 'Tow Truck Training',
                'new_user_eligible' => 0,
                'all_rangers' => 1,
                'count_hours' => 0,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            88 => 
            array (
                'id' => 103,
                'title' => 'HQ TOD',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 1,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => 31,
            ),
            89 => 
            array (
                'id' => 104,
                'title' => 'HQ Window - Sandman',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'HQ',
                'training_position_id' => 31,
            ),
            90 => 
            array (
                'id' => 105,
                'title' => 'DPW Ranger',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => 1,
                'short_title' => 'DPW',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            91 => 
            array (
                'id' => 106,
                'title' => 'Department Manager',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 1,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'DepMgr',
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            92 => 
            array (
                'id' => 107,
                'title' => 'Dirt - Shiny penny',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 1,
                'on_sl_report' => 1,
                'short_title' => 'Penny',
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            93 => 
            array (
                'id' => 108,
                'title' => 'Sandman Trainer',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => 'SndTrg',
                'type' => 'Training',
                'training_position_id' => NULL,
            ),
            94 => 
            array (
                'id' => 109,
                'title' => 'RSC WESL',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Command',
                'training_position_id' => NULL,
            ),
            95 => 
            array (
                'id' => 110,
                'title' => '007 - Standby',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Frontline',
                'training_position_id' => NULL,
            ),
            96 => 
            array (
                'id' => 111,
                'title' => 'Echelon Lead Training',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
            97 => 
            array (
                'id' => 112,
                'title' => 'Volunteer Coordinator',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 1,
                'min' => 1,
                'max' => 0,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Other',
                'training_position_id' => NULL,
            ),
            98 => 
            array (
                'id' => 113,
                'title' => 'Tech On Call',
                'new_user_eligible' => 0,
                'all_rangers' => 0,
                'count_hours' => 0,
                'min' => 1,
                'max' => 1,
                'auto_signout' => 0,
                'on_sl_report' => NULL,
                'short_title' => NULL,
                'type' => 'Logistics',
                'training_position_id' => NULL,
            ),
        ));
        
        
    }
}