language: python
python: 3.6


services:
  - docker


branches:
  only:
    - master


stages:
  - Test
  - Deploy


jobs:
  include:
    - stage: Test
      script: ./bin/travis test
    - stage: Deploy
      script: ./bin/travis deploy staging
      if: branch = master
      if: type = push


install:
  - true


script:
  - true


cache:
  directories:
    - ~/docker_images
