language: python
python: 3.6


services:
  - docker


branches:
  only:
    - master


stages:
  - Test
  - Deploy


jobs:
  include:
    - stage: Test
      script:
        - ./bin/travis test
      if: type = pull_request
    - stage: Deploy
      script:
        - ./bin/travis test
        - ./bin/travis deploy staging
      if: branch = master
      if: type = push


install:
  - true


script:
  - true


cache:
  directories:
    - ~/docker_images
    - $HOME/.composer/cache/files


notifications:
  email:
    recipients:
      - ranger-tech-list@burningman.org
  slack:
    on_success: always
    on_failure: always
    secure: DdsXas9ZKSxHLRwcIiwxWI7N0D2DR8ve2DSU3hYgvAJPylHwKmtwD3ldcmDKoS18RZmqChITzuERUFDKwefL9VRyEsUq2WYahzoRQToUYC3m4vWe8nXZF6TID02U0ZcZCnJnGfK2g4infMUa1nTryzcOXo3bfcZT8Y6LFK4Y5MX3Q48onlpaFaMrEe+4bjjLJyMQlH1YHrhr9PTAcbAJIxojpceWbCzTTbyEKLTTDkg+iDG/ZmtON1sSZFx60VfnljuuCKE+9nMidBT8GhFwEGs2ReCdZRcpts95JXdkKy/1dFMFUZlKOo73kwXqer/PkJDVtTDi16ga+agp3tuKjbG7Vndhp2013jxpUBBg3v8rXRBUbH/yYDg3tliq06rfmxWKN6Rpa8Z+sYXd/E/zC35L63bTYhgPCiT9a7UYBypzFWv0w+RPSVeqARl8IWIgIQ1fAfsA/6GTV56sSD329wj9QLgsBb+u2FnBXPqVT7wYw/AtsI6CiE13M8pK5KNGHaqbcOcRtDrXk47fMK6LCF/QJTX5MO4gpBaKT2B7SLYZEGxpA0Bvcop4wHiXxOOLmtEjlNC6NJFV/AoHK6cX8R0KgeQU45Bd5coJQ6cnabil2L8PIRo9HrDQ5ojz4wzJBjg7NRGRRyT9vy1MoombIA7Bzy6ty+PVFbuUR5zc2Og=
