language: python
python: 3.6


services:
  - docker


branches:
  only:
    - master


stages:
  - Test
  - Deploy


jobs:
  include:
    - stage: Test
      env: TRAVIS_ACTION=test
    - stage: Deploy
      env: TRAVIS_ACTION=deploy
      if: branch = master


script:
  - ./bin/travis


cache:
  directories:
    - docker
