services:
  - docker


branches:
  only:
    - master


stages:
  - Lint
  - Test
  - Deploy


jobs:
  include:
    - stage: Lint
      env: TRAVIS_ACTION=lint
    - stage: Test
      env: TRAVIS_ACTION=docker
    - stage: Deploy
      env: TRAVIS_ACTION=deploy
      if: branch = master


script:
  - ./bin/travis
