sudo: required
language: python
python: 3.6


services:
  - docker
  - mysql


branches:
  only:
    - master


stages:
  - Test
  - Deploy


jobs:
  include:
    - stage: Test
      script: ./bin/travis test
    - stage: Deploy
      script: ./bin/travis deploy
      if: branch = master


before_install:
  - echo "Altering MySQL configuration to bind to all interfaces:"
  - printf "[server]\nbind-address = ::\n" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart


install:
  - true


script:
  - true


cache:
  directories:
    - ~/docker_images
