sudo: required
language: python
python: 3.6


services:
  - docker
  - mysql


branches:
  only:
    - master


stages:
  - Test
  - Deploy


jobs:
  include:
    - stage: Test
      script: ./bin/travis test
    - stage: Deploy
      script: ./bin/travis deploy
      if: branch = master


before_install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y


install:
  - true


script:
  - true


cache:
  directories:
    - ~/docker_images
