language: python
python: 3.6


services:
  - docker


branches:
  only:
    - master


stages:
  - Test
  - Deploy


jobs:
  include:
    - stage: Test
      script: ./bin/travis test
      if: type = pull_request
    - stage: Deploy
      script:
        - ./bin/travis test
        - ./bin/travis deploy staging
      if: branch = master
      if: type = push


install:
  - true


script:
  - true


#cache:
#  directories:
#    - ~/docker_images


notifications:
  email:
    recipients:
      - ranger-tech-list@burningman.org
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: "ef6sqzVyOh+J8QplDuFnysyBBT89H3UZ3NPAH0jymKBp+HYukVawLNyxBGUzRQ/+Qege3E1NncyG+PTvqyQqsuJxY8I25SWDP5Cg5UWkihUGe1MmmWQIeMXtAdNUMeyUwWEl/GhlnAcpa1VKXuA0S5K5fWqEDXDQBNAecKnQ0SnsZpA51SUTcceD15EjK526JigKgTBY8Lut7deJFR2pdc2cxkUk/utFNYcKGJbTlN1UtY18xrLKaewF/eFsEjMY9tMYWS/djtVcBu3jqMOcMKRoJT17SbwvzTpVh/R1E2zgdjn1TAChVZgyBpP+QuCA2VTupBsXT35nJR/chF5DhePVmwqlU5wOsLPG95TMBUP1Q5S+tXuAUuTxF70g/QGnxioqj6KZfSc5csdqe+oGrKHrCax16V09immx1UvW8HcVZDrzZOoR3GyNsBWAJ/kg2fK4s67QIgQHV+EI/ZCjRM3kSIN4Rf8mrHje620njmP1hOAQ9XbNhoFiLvzkrfYCQGhuEk1L7QQOy6mTtvrHfauE5H5zT+9p7/7b8ey/bGcDtqDbI4CAOSAeg9OLUaqkNw78O/sYDIi/tqwVsOUE7+UN8xazjNGi9hlWY8D2MjjiSFur2ntUwqedzfkE/zqv1Qy7l59xyD84mX57kPIUVy1Q2Tldb9vhKyRYgnbmt+4="
