# language: php


services:
  - docker


branches:
  only:
    - master


matrix:
  include:
    - env: TRAVIS_ACTION=lint
    - env: TRAVIS_ACTION=docker


script:
  - ./bin/travis


deploy:
  provider: script
  script: env TRAVIS_ACTION=deploy ./bin/travis
  on:
    branch: master
