#!/bin/sh

#
# Start Clubhouse queue worker -- handles all Laravel queue jobs
#

# Allow set up to finish in peace.
# (app optimizations, migrations, training database generated and/or loaded)
sleep 120;

echo "Starting Clubhouse queue worker...";

php /var/www/application/artisan db:wait;

while [ true ]
do
    php /var/www/application/artisan queue:work --stop-when-empty;
    sleep 15;
done
