#!/bin/sh

#
# Start Clubhouse queue worker -- handles all Laravel queue jobs
#


echo "Starting Clubhouse queue worker...";

php /var/www/application/artisan db:wait;

while [ true ]
do
    php /var/www/application/artisan queue:work --stop-when-empty;
    sleep 60;
done
