#!/bin/sh

#
# Start Clubhouse schedule worker.
#
# Handles all Laravel scheduled jobs as defined in app/Console/Kernel.php -- does not handle queued jobs.

# Allow set up to finish in peace.
# (app optimizations, migrations, training database generated and/or loaded)
sleep 120;

echo "Starting Clubhouse schedule worker...";

php /var/www/application/artisan db:wait;

while [ true ]
do
    php /var/www/application/artisan schedule:run -vvv --no-interaction;
    sleep 15;
done