#!/bin/sh

#
# Install script for building the Docker container.
# This is not intended to be run directly.
#

set -eu


echo "Installing PHP Composer";

url="https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer";

wget "${url}" -O - -q | php --;
