#!/bin/sh

#
# Install script for building the Docker container.
# This is not intended to be run directly.
#

set -eu

# Needed to build PHP extensions
apk add --no-cache libxml2-dev libpng libpng-dev libjpeg-turbo-dev libwebp-dev;

docker-php-ext-configure gd --with-webp-dir=/usr/include/  --with-jpeg-dir=/usr/include/;

docker-php-ext-install             \
    ctype                          \
    gd                             \
    json                           \
    mbstring                       \
    pdo                            \
    pdo_mysql                      \
    tokenizer                      \
    xml                            \
    ;

# Clean up requirements for building PHP extensions
apk del libxml2-dev
apk add --no-cache libxml2;

# Fix permissions
install -d -o www-data -g www-data -m 775  \
    ./storage/framework/cache              \
    ./storage/framework/sessions           \
    ./storage/framework/views              \
    ./storage/logs                         \
    ;
