#!/bin/sh

#
# Start Nginx web server... but first warm up Laravel
#

set -eu

# Send stdio to supervisor's stdio
if [ ! -t 0 ]; then
    exec 1> /proc/1/fd/1 2> /proc/1/fd/2;
fi;

# Cache Laravel configuration and routes

cd /var/www/application;

echo "Waiting for database to come online...";
php artisan db:wait;

if [ -n "${RANGER_CLUBHOUSE_GROUNDHOG_DAY_TIME-}" ]; then
    echo "Creating training database";
    php artisan clubhouse:create-training-db;
fi

echo "Purging obsoleted Clubhouse settings ...";
php artisan clubhouse:purge-settings

echo "Caching Laravel configuration and routes...";
php artisan config:cache;
php artisan route:cache;
php artisan view:cache;
php artisan event:cache;

echo "Performing database migrations...";
php artisan migrate --force;

echo "Starting queue runners and scheduler"
supervisorctl start clubhouse-worker
supervisorctl start clubhouse-scheduler

echo "Starting php-fpm"
supervisorctl start php-fpm

sleep 5

echo "Starting Nginx...";
exec nginx "$@";
