<?php

namespace App\Models;

class Alert extends ApiModel
{
    protected $table = 'alert';
    protected bool $auditModel = true;

    const int SHIFT_CHANGE = 1;
    const int SHIFT_MUSTER = 2;
    const int EMEREGENCY_BROADCAST = 3;
    const int RANGER_SOCIALS = 4;
    const int TICKETING = 5;
    const int ON_SHIFT = 6;
    const int TRAINING = 7;
    const int CLUBHOUSE_NOTIFY_ON_PLAYA = 8;
    const int CLUBHOUSE_NOTIFY_PRE_EVENT = 9;
    const int SHIFT_CHANGE_PRE_EVENT = 10;
    const int SHIFT_MUSTER_PRE_EVENT = 11;

    // The following are not part of the RBS and are email only
    const int RANGER_CONTACT = 12;
    const int MENTOR_CONTACT = 13;

    protected $fillable = [
        'title',
        'description',
        'on_playa',
    ];

    protected function casts(): array
    {
        return [
            'on_playa' => 'boolean',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ];
    }

    protected $rules = [
        'title' => 'required|string',
        'description' => 'required|string',
        'on_playa' => 'boolean'
    ];

    protected $appends = [
        'sms_only',
        'email_only',
        'no_opt_out',
    ];

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleted(function ($model) {
            AlertPerson::where('alert_id', $model->id)->delete();
        });
    }

    public static function findAll()
    {
        return self::orderBy('on_playa', 'desc', 'title', 'asc')->get();
    }

    public function getSmsOnlyAttribute()
    {
        return ($this->id == Alert::ON_SHIFT);
    }

    public function getEmailOnlyAttribute()
    {
        return ($this->id == Alert::RANGER_CONTACT || $this->id == Alert::MENTOR_CONTACT);
    }

    public function getNoOptOutAttribute()
    {
        return ($this->id == Alert::EMEREGENCY_BROADCAST);
    }
}
